// <auto-generated />
using System;
using Inventory_And_Warehouse_Management;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory_And_Warehouse_Management.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260810151658_FixModelIssues")]
    partial class FixModelIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.InventoryLevel", b =>
                {
                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryLevelId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("ReorderThreshold")
                        .HasColumnType("int");

                    b.HasKey("WarehouseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryLevels");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.ProductSupplier", b =>
                {
                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("supplierId")
                        .HasColumnType("int");

                    b.HasKey("productId", "supplierId");

                    b.HasIndex("supplierId");

                    b.ToTable("productSuppliers");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("purchaseOrders");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.PurchaseOrderItem", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseOrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("purchaseOrderItems");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.SalesOrder", b =>
                {
                    b.Property<int>("SalesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesOrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SalesOrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("salesOrders");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.SalesOrderItem", b =>
                {
                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalesOrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("salesOrderItems");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.StockMovement", b =>
                {
                    b.Property<int>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockMovementId"));

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("StockMovementId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("stockMovements");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseId");

                    b.ToTable("warehouses");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.InventoryLevel", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Product", "product")
                        .WithMany("inventoryLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_And_Warehouse_Management.Models.Warehouse", "warehouse")
                        .WithMany("inventoryLevels")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("warehouse");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Product", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.ProductSupplier", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Product", "product")
                        .WithMany("productSuppliers")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_And_Warehouse_Management.Models.Supplier", "supplier")
                        .WithMany("productSuppliers")
                        .HasForeignKey("supplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.PurchaseOrder", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Supplier", "supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_And_Warehouse_Management.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("supplier");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.PurchaseOrderItem", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Product", "product")
                        .WithMany("purchaseOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_And_Warehouse_Management.Models.PurchaseOrder", "purchaseOrder")
                        .WithMany("purchaseOrderItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("purchaseOrder");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.SalesOrder", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Customer", "customer")
                        .WithMany("salesOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_And_Warehouse_Management.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.SalesOrderItem", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Product", "product")
                        .WithMany("SalesOrderItem")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_And_Warehouse_Management.Models.SalesOrder", "salesOrder")
                        .WithMany("salesOrderItems")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("salesOrder");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.StockMovement", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Product", "product")
                        .WithMany("stockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_And_Warehouse_Management.Models.Warehouse", "_warehouse")
                        .WithMany("stockMovements")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_warehouse");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.User", b =>
                {
                    b.HasOne("Inventory_And_Warehouse_Management.Models.Warehouse", "_warehouse")
                        .WithMany("users")
                        .HasForeignKey("WarehouseId");

                    b.Navigation("_warehouse");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Customer", b =>
                {
                    b.Navigation("salesOrders");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Product", b =>
                {
                    b.Navigation("SalesOrderItem");

                    b.Navigation("inventoryLevels");

                    b.Navigation("productSuppliers");

                    b.Navigation("purchaseOrderItems");

                    b.Navigation("stockMovements");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.PurchaseOrder", b =>
                {
                    b.Navigation("purchaseOrderItems");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.SalesOrder", b =>
                {
                    b.Navigation("salesOrderItems");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");

                    b.Navigation("productSuppliers");
                });

            modelBuilder.Entity("Inventory_And_Warehouse_Management.Models.Warehouse", b =>
                {
                    b.Navigation("inventoryLevels");

                    b.Navigation("stockMovements");

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
